### ISSUE TITLE
Errors trying to use package

### ISSUE THREAD

**Issue by alansutherland** [danielfamiyeh/node-finage#16]
after installing the module and setting up a test call following your docs I see this error on my app

```
Loading...
ERROR in ./node_modules/finage/node_modules/node-fetch/src/utils/referrer.js
Module not found: Error: Can't resolve 'net' in '/Users/alan/Documents/Web/the-markets/frontend/node_modules/finage/node_modules/node-fetch/src/utils'
ERROR in ./node_modules/finage/node_modules/node-fetch/src/index.js
Module not found: Error: Can't resolve 'node:http' in '/Users/alan/Documents/Web/the-markets/frontend/node_modules/finage/node_modules/node-fetch/src'
ERROR in ./node_modules/finage/node_modules/node-fetch/src/headers.js
Module not found: Error: Can't resolve 'node:http' in '/Users/alan/Documents/Web/the-markets/frontend/node_modules/finage/node_modules/node-fetch/src'
ERROR in ./node_modules/finage/node_modules/node-fetch/src/index.js
Module not found: Error: Can't resolve 'node:https' in '/Users/alan/Documents/Web/the-markets/frontend/node_modules/finage/node_modules/node-fetch/src'
ERROR in ./node_modules/finage/node_modules/node-fetch/src/index.js
Module not found: Error: Can't resolve 'node:stream' in '/Users/alan/Documents/Web/the-markets/frontend/node_modules/finage/node_modules/node-fetch/src'
ERROR in ./node_modules/finage/node_modules/node-fetch/src/body.js
Module not found: Error: Can't resolve 'node:stream' in '/Users/alan/Documents/Web/the-markets/frontend/node_modules/finage/node_modules/node-fetch/src'
ERROR in ./node_modules/finage/node_modules/node-fetch/src/request.js
Module not found: Error: Can't resolve 'node:url' in '/Users/alan/Documents/Web/the-markets/frontend/node_modules/finage/node_modules/node-fetch/src'
ERROR in ./node_modules/finage/node_modules/node-fetch/src/headers.js
Module not found: Error: Can't resolve 'node:util' in '/Users/alan/Documents/Web/the-markets/frontend/node_modules/finage/node_modules/node-fetch/src'
ERROR in ./node_modules/finage/node_modules/node-fetch/src/body.js
Module not found: Error: Can't resolve 'node:util' in '/Users/alan/Documents/Web/the-markets/frontend/node_modules/finage/node_modules/node-fetch/src'
ERROR in ./node_modules/finage/node_modules/node-fetch/src/index.js
Module not found: Error: Can't resolve 'node:zlib' in '/Users/alan/Documents/Web/the-markets/frontend/node_modules/finage/node_modules/node-fetch/src'
ERROR in ./node_modules/formdata-polyfill/esm.min.js 17:0
Module parse failed: Unexpected character '#' (17:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| /** @type {typeof globalThis.FormData} */
| export const FormData = class FormData {
> #d=[];
| constructor(...a){if(a.length)throw new TypeError(`Failed to construct 'FormData': parameter 1 is not of type 'HTMLFormElement'.`)}
| get [t]() {return 'FormData'}
ERROR in ./node_modules/fetch-blob/index.js 48:2
Module parse failed: Unexpected character '#' (48:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const _Blob = class Blob {
|   /** @type {Array.<(Blob|Uint8Array)>} */
>   #parts = []
|   #type = ''
|   #size = 0
ERROR in ./node_modules/fetch-blob/from.js 64:2
Module parse failed: Unexpected character '#' (64:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| class BlobDataItem {
>   #path
|   #start
| 
```

**Comment by danielfamiyeh** [comment]
@alansutherland - Apologies for this, I will have a look later today

**Comment by danielfamiyeh** [comment]
@alansutherland - What framework are you using for development, it looks like Angular?

**Comment by alansutherland** [comment]
Thanks @danielfamiyeh I'm using vue/nuxt

**Comment by alansutherland** [comment]
Think it might related to this error shown during installation of the package

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'node-fetch@3.1.0',
npm WARN EBADENGINE   required: { node: '^12.20.0 || ^14.13.1 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '8.1.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'fetch-blob@3.1.3',
npm WARN EBADENGINE   required: { node: '^12.20 || >= 14.13' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '8.1.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'formdata-polyfill@4.0.10',
npm WARN EBADENGINE   required: { node: '>=12.20.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '8.1.3' }
npm WARN EBADENGINE }
```

I uninstalled node 12 and reinstalled it to the correct version though and still see the errors

**Comment by alansutherland** [comment]
any updates on this @danielfamiyeh ?

**Comment by danielfamiyeh** [comment]
@alansutherland - Apologies! I've been really snowed under with work and had some problems with npm that took a while to resolve over the weekend. It is on my radar though, I'll give you an update tomorrow evening of progress.
Thank you for being patient with me.

**Comment by alansutherland** [comment]
no worries, thanks for your help

**Comment by danielfamiyeh** [comment]
@alansutherland - I want to apologise again for taking so long to fix this, I've really been busy with a lot of things and projects! I've fixed this in a patch I just published to npm and tested it with vue/nuxt using the example request in the README. It should be working now.

**Comment by alansutherland** [comment]
@danielfamiyeh thanks very much, I will check today

**Comment by danielfamiyeh** [comment]
@alansutherland - Sweet, let me know how it goes 😄

**Comment by alansutherland** [comment]
@danielfamiyeh thanks very much for your help updating the package to use axios. I have tested and got the module working. What are the advantages of using this module over directly accessing the api? is this mainly to keep my api key safe or will it also offer optimisation to my apps speed?

**Comment by danielfamiyeh** [comment]
@alansutherland - I'm glad to hear it. There aren't necessarily any advantages like that with regards to using this package. I wrote it originally for myself as a form of syntactic sugar, so to speak. To make it easier and cleaner to programmatically retrieve data from Finage's API endpoints, rather than hardcoding for different use cases, which could be error-prone.

I have had ideas to provide interfaces with other APIs to extend the functionality of Finage's.

For instance, I've used Finage's API in conjunction with IBM Watson's NLP API to provide sentiment analysis on market news.
So I'm thinking integrations like that, that people would find useful.

What do you think? I'd be happy to listen to any ideas at all!

**Comment by alansutherland** [comment]
I see, yes it's definitely easier to use than hardcoding different use cases.

Using it in conjunction with Watson's NLP API sounds like something we'd be very interested in using on our site.

We're building an app [themarkets.io](themarkets.io) for the finance markets which requires these instruments:

### Cryptocurrency
Top 50 by marketcap
https://coinmarketcap.com/

### Forex
EURUSD,USDJPY,USDKRW,USDTRY,GBPUSD,USDBRL,USDILS,USDRUB

### Commodities
Carbon Emissions,Gold,Silver,Bitcoin Futures,Natural Gas,Crude Oil,Brent Oil,US Coffee C

### Stocks - Apple,Pfizer,Amazon,Facebook,Microsoft,Moderna,NIO,Tesla,Nvidia,Xpeng,Palantir,Boeing,Santander,Alibaba,Gamestop,AMC,BlackBerry

### Indices
NASDAQ, NASDAQ CFD, NASDAQ Futures, DOW JONES, DOW JONES CFD, DOW JONES Futures, S&P 500, S&P 500 CFD, S&P 500 Futures, FTSE, FTSE CFD, FTSE Futures, NIKKEI, NIKKEI CFD, NIKKEI Futures, HANG SENG, HANG SENG CFD, HANG SENG Futures, SHANGHAI, SHANGHAI CFD, SHANGHAI Futures, KOSPI, KOSPI CFD, KOSPI Futures, DAX, DAX CFD, DAX Futures, IBEX 35, IBEX 35 CFD, IBEX Futures, BIST 100, BIST 100 CFD, BIST 100 Futures, Dollar Index

### Bonds
US 1M Bond, US 3M Bond, US 6M Bond, US 1 Year Bond, US 2 Year Bond, US 5 Year Bond, US 7 Year Bond, US 10 Year Bond, US 20 Year Bond, US 30 Year Bond

I can retrieve most from finage but I have to query multiple endpoints and also connect to 4 different websockets each with multiple subscriptions. I think I'm making roughly 200+ api calls every time the app loads. I could send you the project if you were interested in helping us refactor and optimise the code? we'd be happy to hire you as a freelancer. I'm thinking that perhaps we need to switch to using GraphQL to reduce the number of calls or move the data fetching logic completely to the backend.

Another solution I'm looking at is [Lightstreamer](https://lightstreamer.com/) which is used by apps like eToro for handling live streaming data for multiple instruments simultaneously. They have [a Vue example](https://github.com/Lightstreamer/Lightstreamer-example-StockList-client-vue/tree/master/src)

**Comment by danielfamiyeh** [comment]
@alansutherland - Ah, sweet man. I honestly didn't think anyone would find it useful!  But knowing that now I'll start work on integration with Watson as a next task for the package. Would you be down to test it when it's finished?

The app is looking nice man! You've blended the API with the UI in a really pleasing way. But I can imagine all of those requests must end up being pretty costly. Yeah, I think you're right, GraphQL would probably be a good shout here. And there'll be ways to optimise the architecture to reduce calls.
Ah, I've never heard of Lightstreamer, I'll have a look into it too.

But I'd be more than happy to help out and refactor things for sure!

I've added my e-mail address to my GitHub profile. Feel free to drop me a message and go into more details about the project.

**Comment by alansutherland** [comment]
Yes, it sounds very useful for what we're building. Especially if we could predict sentiment in the crypto and memestock area. I'll email you.
